# Uncomment the next line to define a global platform for your project


target 'SeeFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeeFood
    pod ‘SVProgressHUD’

end
