# Uncomment the next line to define a global platform for your project


target 'SeeFoodWatson' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeeFoodWatson
    pod 'IBMWatsonVisualRecognitionV3', '~> 2.2.0'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
end
